version: "3.9"

services:
  server:
    container_name: vintagestory
    image: vintagestory:1.18.10
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 1.18.10
    network_mode: "host" # use host network for better performance
    restart: unless-stopped
    command: /var/vintagestory/start.sh
    volumes:
      - data:/var/vintagestory/data
      - backup:/var/vintagestory/data/Backups

volumes:
  data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data"
  backup:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/path/to/your/backup"
